version: '3'
services:
  app:
    build: .
    command: sleep infinity
    volumes:
      - ..:/app
    links:
      - kafka
  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
